### ISSUE TITLE
define a deprecation schedule for cached holochain versions

### ISSUE THREAD

**Issue by steveej** [holochain/holochain-nixpkgs#53]
@zo-el @zippy @timotree3 @jost-s

as of now i don't have a way to deterministically manage the [list of holochain versions that will be built and cached by CI](https://github.com/holochain/holochain-nixpkgs/blob/develop/.github/workflows/build.yml#L50).

my preferred upper limit for this list would be 10, which would yield 20 concurrent jobs per CI run which is the number that github actions let us run concurrently. 
the most simple algorithm would therefore be to cut the list to 10 now and then always remove the oldest version whenever we add a new one.

note that removing a version from this list keeps the named version known and usable. so this would not break any old holonix files, just make their load times longer if they're not already cached on the consumer side or by their own CI.

**Comment by jost-s** [comment]
We've talked about this before. Still makes sense to me 🙂

**Comment by timotree3** [comment]
10 weeks old should be old enough that devs are likely to have already downloaded if they need it, so this seems fine. Also, it's worth noting that several repos have a write token to Cachix in their CI, so I guess that means that each time CI runs on one of those repos, it will insert its version of holochain into the cache.
